/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.nbcb.constant.ShopCode;
import com.nbcb.exception.CastException;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class CastException_SSTest extends CastException_SSTest_scaffolding {
// allCoveredLines:[7, 9, 10]

  @Test(timeout = 9000)
  public void test_cast_0()  throws Throwable  {
      //caseID:140a8c0be9d353ab67ad1b9274f99d08
      //CoveredLines: [7, 9, 10]
      //Input_0_ShopCode: ShopCode.SHOP_MQ_MESSAGE_STATUS_PROCESSING
      
      CastException castException0 = new CastException();
      ShopCode shopCode0 = ShopCode.SHOP_MQ_MESSAGE_STATUS_PROCESSING;
      
      //Call method: cast
      try { 
        CastException.cast(shopCode0);
      } catch(Throwable e) {
         verifyException("com.nbcb.exception.CastException", e);
         assertEquals("com.nbcb.exception.CustomerException", e.getClass().getName());
      }
  }
}
