/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.nbcb.constant.ShopCode;
import com.nbcb.exception.CustomerException;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class CustomerException_SSTest extends CustomerException_SSTest_scaffolding {
// allCoveredLines:[9, 10, 11]

  @Test(timeout = 9000)
  public void test0()  throws Throwable  {
      //caseID:c4c1113e0fb6191dd6e32e119f0bb142
      //CoveredLines: [9, 10, 11]
      
      ShopCode shopCode0 = ShopCode.SHOP_COUPON_INVALIED;
      CustomerException customerException0 = new CustomerException(shopCode0);
  }
}
