server:
  port: 8085
spring:
  application:
    name: dubbo-pay-provider
  datasource:
    name: shop
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      id: dubbo-pay-provider
      name: dubbo-pay-provider
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181;zookeeper://127.0.0.1:2182;zookeeper://127.0.0.1:2183
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20884
#    scan: com.dubboProvide.dubboProvide.service  #服务暴露与发现消费所在的package
# mybatis配置
mybatis:
  mapper-locations: classpath:/com.nbcb.mapper/*.xml
  type-aliases-package: com.nbcb.pojo
# RocketMQ配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: payProducerGroup
    send-message-timeout: 50000
# 自定义消息参数
mq:
  pay:
    consumer:
      group:
        name: pay_payTopic_group
    topic: payTopic
    tag: paid
