server:
  host: http://localhost
  port: 8095
spring:
  application:
    name: dubbo-order-consumer
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      id: dubbo-order-consumer
      name: dubbo-order-consumer
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181;zookeeper://127.0.0.1:2182;zookeeper://127.0.0.1:2183
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20885
#    scan: com.dubboProvide.dubboProvide.service  #服务暴露与发现消费所在的package
shop:
  order:
    port: 8095
    baseURI: ${server.host}:${shop.order.port}
    confirm: /order/confirm

# RocketMQ配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: seckillProducerGroup
    send-message-timeout: 50000
# 自定义消息参数
mq:
  seckill:
    consumer:
      group:
        name: seckillTopic_group
    topic: seckillTopic
    tag: seckilled