/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class PayWebApplication_SSTest extends PayWebApplication_SSTest_scaffolding {
  @Test
  public void notGeneratedAnyTest() {
    // SmartUnit did not generate any tests
  }
}
