/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.nbcb.OrderServiceApplication;
import com.nbcb.utils.IDWorker;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class OrderServiceApplication_SSTest extends OrderServiceApplication_SSTest_scaffolding {
// allCoveredLines:[14, 21, 26, 27, 28, 29, 30, 31, 32, 33, 34]

  @Test(timeout = 9000)
  public void test_getBean_0()  throws Throwable  {
      //caseID:28cb498de0ed1069b38c71e05dbbff0b
      //CoveredLines: [14, 21]
      //Assert: assertNotNull(method_result);
      
      OrderServiceApplication orderServiceApplication0 = new OrderServiceApplication();
      
      //Call method: getBean
      IDWorker iDWorker0 = orderServiceApplication0.getBean();
      
      //Test Result Assert
      assertNotNull(iDWorker0);
  }

  @Test(timeout = 9000)
  public void test_getThreadPool_1()  throws Throwable  {
      //caseID:588cd638c88bc2e00320ca0d8a027aad
      //CoveredLines: [14, 26, 27, 28, 29, 30, 31, 32, 33, 34]
      //Assert: assertEquals(8, method_result.getMaxPoolSize());
      //Assert: assertEquals(4, method_result.getCorePoolSize());
      //Assert: assertEquals("Pool_A", method_result.getThreadNamePrefix());
      //Assert: assertEquals(60, method_result.getKeepAliveSeconds());
      
      OrderServiceApplication orderServiceApplication0 = new OrderServiceApplication();
      
      //Call method: getThreadPool
      ThreadPoolTaskExecutor threadPoolTaskExecutor0 = orderServiceApplication0.getThreadPool();
      
      //Test Result Assert
      assertEquals(8, threadPoolTaskExecutor0.getMaxPoolSize());
      
      //Test Result Assert
      assertEquals(4, threadPoolTaskExecutor0.getCorePoolSize());
      
      //Test Result Assert
      assertEquals("Pool_A", threadPoolTaskExecutor0.getThreadNamePrefix());
      
      //Test Result Assert
      assertEquals(60, threadPoolTaskExecutor0.getKeepAliveSeconds());
  }
}
