/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.nbcb.entity.GoodsResult;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class GoodsResult_SSTest extends GoodsResult_SSTest_scaffolding {
// allCoveredLines:[5, 10, 14, 18, 22]

  @Test(timeout = 9000)
  public void test_equals_0()  throws Throwable  {
      //caseID:996985c74ec6490f11d0b1b9bbeccc5b
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_Object: goodsResult0
      //Assert: assertTrue(method_result);
      
      GoodsResult goodsResult0 = new GoodsResult();
      
      //Call method: equals
      boolean boolean0 = goodsResult0.equals(goodsResult0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_1()  throws Throwable  {
      //caseID:21e26819993645ebf4a6b5aec446928d
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_Object: 1
      //Assert: assertFalse(method_result);
      
      GoodsResult goodsResult0 = new GoodsResult();
      
      //Call method: equals
      boolean boolean0 = goodsResult0.equals("1");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_2()  throws Throwable  {
      //caseID:6554896d87454dd6347bc5371fb6df39
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 14, 18, 22]
      //Input_0_Object: goodsResult0
      //Assert: assertTrue(method_result);
      
      GoodsResult goodsResult0 = new GoodsResult();
      GoodsResult goodsResult1 = new GoodsResult();
      
      //Call method: equals
      boolean boolean0 = goodsResult1.equals(goodsResult0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_3()  throws Throwable  {
      //caseID:e683a7c950896d2b59ccce7fb379aa2b
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 14, 18, 22]
      //Input_0_Object: goodsResult1
      //Assert: assertTrue(method_result);
      
      GoodsResult goodsResult0 = new GoodsResult();
      GoodsResult goodsResult1 = new GoodsResult();
      
      //Call method: equals
      boolean boolean0 = goodsResult0.equals(goodsResult1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_4()  throws Throwable  {
      //caseID:3b0f6eabc81b911d42d5af9f7b61765f
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 14, 18, 22]
      
      GoodsResult goodsResult0 = new GoodsResult();
      
      //Call method: hashCode
      goodsResult0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setAlt_5()  throws Throwable  {
      //caseID:0f9597a3cbacc52418457f61f823433f
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_String: U[gIH+hUHFb
      
      GoodsResult goodsResult0 = new GoodsResult();
      
      //Call method: setAlt
      goodsResult0.setAlt("U[gIH+hUHFb");
      
      //Test Result Assert
      assertNull(goodsResult0.getPicture());
  }

  @Test(timeout = 9000)
  public void test_setId_6()  throws Throwable  {
      //caseID:22fc67ca7c31cbe37883cf32227bc275
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_String: )
      
      GoodsResult goodsResult0 = new GoodsResult();
      
      //Call method: setId
      goodsResult0.setId(")");
      
      //Test Result Assert
      assertNull(goodsResult0.getAlt());
  }

  @Test(timeout = 9000)
  public void test_setPicture_7()  throws Throwable  {
      //caseID:e31b10a53f049742cf6046fde270834f
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_String: {\"mx1~&`P$$[}
      
      GoodsResult goodsResult0 = new GoodsResult();
      
      //Call method: setPicture
      goodsResult0.setPicture("{\"mx1~&`P$$[}");
      
      //Test Result Assert
      assertNull(goodsResult0.getTitle());
  }

  @Test(timeout = 9000)
  public void test_setTitle_8()  throws Throwable  {
      //caseID:80ec06c22dce43a03c1141a0e0a317e4
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_String: , picture=
      
      GoodsResult goodsResult0 = new GoodsResult();
      
      //Call method: setTitle
      goodsResult0.setTitle(", picture=");
      
      //Test Result Assert
      assertNull(goodsResult0.getId());
  }

  @Test(timeout = 9000)
  public void test_toString_9()  throws Throwable  {
      //caseID:e2ebd6f679b32f4b48bd2bfd40afcf9b
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 14, 18, 22]
      //Assert: assertEquals("GoodsResult(alt=null, id=null, picture=null, title=null)", method_result);
      
      GoodsResult goodsResult0 = new GoodsResult();
      
      //Call method: toString
      String string0 = goodsResult0.toString();
      
      //Test Result Assert
      assertEquals("GoodsResult(alt=null, id=null, picture=null, title=null)", string0);
  }
}
