/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.nbcb.entity.GoodsDetailResponse;
import com.nbcb.entity.GoodsDetailResult;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class GoodsDetailResponse_SSTest extends GoodsDetailResponse_SSTest_scaffolding {
// allCoveredLines:[7, 12, 16, 20]

  @Test(timeout = 9000)
  public void test_equals_0()  throws Throwable  {
      //caseID:91c621df6efc3c9471df73c756d294be
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_Object: 0
      //Assert: assertFalse(method_result);
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: equals
      boolean boolean0 = goodsDetailResponse0.equals("0");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_1()  throws Throwable  {
      //caseID:c893a05cc467408d8db657a2db657af0
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_Object: goodsDetailResponse0
      //Assert: assertTrue(method_result);
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: equals
      boolean boolean0 = goodsDetailResponse0.equals(goodsDetailResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_2()  throws Throwable  {
      //caseID:31f5865257b6927bd505147eec202c9f
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      //Input_0_Object: goodsDetailResponse0
      //Assert: assertTrue(method_result);
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      GoodsDetailResponse goodsDetailResponse1 = new GoodsDetailResponse();
      
      //Call method: equals
      boolean boolean0 = goodsDetailResponse1.equals(goodsDetailResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_3()  throws Throwable  {
      //caseID:33004ffbd2539ec440a6516e756a8f59
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      //Input_0_Object: goodsDetailResponse1
      //Assert: assertTrue(method_result);
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      GoodsDetailResponse goodsDetailResponse1 = new GoodsDetailResponse();
      
      //Call method: equals
      boolean boolean0 = goodsDetailResponse0.equals(goodsDetailResponse1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_4()  throws Throwable  {
      //caseID:1ac378879c9695214c785d60f45743d5
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: hashCode
      goodsDetailResponse0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setCode_5()  throws Throwable  {
      //caseID:6c9d1080749ea01608fc66188a4890cd
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_String: ^paV*3y c|+;eQp
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: setCode
      goodsDetailResponse0.setCode("^paV*3y c|+;eQp");
      
      //Test Result Assert
      assertEquals("^paV*3y c|+;eQp", goodsDetailResponse0.getCode());
  }

  @Test(timeout = 9000)
  public void test_setMsg_6()  throws Throwable  {
      //caseID:bcd9532e603b279003c2ed160f75780d
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_String: )
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: setMsg
      goodsDetailResponse0.setMsg(")");
      
      //Test Result Assert
      assertNull(goodsDetailResponse0.getCode());
  }

  @Test(timeout = 9000)
  public void test_setResult_7()  throws Throwable  {
      //caseID:2f447ce49153540fe9c8ce7ccb4f8484
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_GoodsDetailResult: {}
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      //mock goodsDetailResult0
      GoodsDetailResult goodsDetailResult0 = mock(GoodsDetailResult.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: setResult
      goodsDetailResponse0.setResult(goodsDetailResult0);
      
      //Test Result Assert
      assertNull(goodsDetailResponse0.getMsg());
  }

  @Test(timeout = 9000)
  public void test_toString_8()  throws Throwable  {
      //caseID:e87a05a42f9f7831c5fa97fdec0a26c6
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      //Assert: assertEquals("GoodsDetailResponse(code=null, msg=null, result=null)", method_result);
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: toString
      String string0 = goodsDetailResponse0.toString();
      
      //Test Result Assert
      assertEquals("GoodsDetailResponse(code=null, msg=null, result=null)", string0);
  }
}
