/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.nbcb.entity.GoodsDetailResponse;
import com.nbcb.entity.GoodsDetailResult;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class GoodsDetailResponse_SSTest extends GoodsDetailResponse_SSTest_scaffolding {
// allCoveredLines:[7, 12, 16, 20]

  @Test(timeout = 9000)
  public void test_equals_0()  throws Throwable  {
      //caseID:9266ede5ea5b43e9142e8ca97cef9bf1
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_Object: hcA\u0004uRuFV8X6lSBjj$
      //Assert: assertFalse(method_result);
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: equals
      boolean boolean0 = goodsDetailResponse0.equals("hcA\u0004uRuFV8X6lSBjj$");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_1()  throws Throwable  {
      //caseID:7a99597a04cdc2a3407620b4d8cd16e4
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_Object: goodsDetailResponse0
      //Assert: assertTrue(method_result);
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: equals
      boolean boolean0 = goodsDetailResponse0.equals(goodsDetailResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_2()  throws Throwable  {
      //caseID:90fb1ea735193cc3427f44350e57a49b
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      //Input_0_Object: goodsDetailResponse0
      //Assert: assertTrue(method_result);
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      GoodsDetailResponse goodsDetailResponse1 = new GoodsDetailResponse();
      
      //Call method: equals
      boolean boolean0 = goodsDetailResponse1.equals(goodsDetailResponse0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_3()  throws Throwable  {
      //caseID:3f290d57615bcdbf8502a6d37642cc8c
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      //Input_0_Object: goodsDetailResponse1
      //Assert: assertTrue(method_result);
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      GoodsDetailResponse goodsDetailResponse1 = new GoodsDetailResponse();
      
      //Call method: equals
      boolean boolean0 = goodsDetailResponse0.equals(goodsDetailResponse1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_4()  throws Throwable  {
      //caseID:b950143cfd49aad62dac5f601e5d76d3
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: hashCode
      goodsDetailResponse0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setCode_5()  throws Throwable  {
      //caseID:818ab18f1864164a395649a435497d44
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_String: io.lettuce.core.dynamic.ReactiveTypeAdapters$PublisherToRxJava2FlowableAdapter
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: setCode
      goodsDetailResponse0.setCode("io.lettuce.core.dynamic.ReactiveTypeAdapters$PublisherToRxJava2FlowableAdapter");
      
      //Test Result Assert
      assertNull(goodsDetailResponse0.getMsg());
  }

  @Test(timeout = 9000)
  public void test_setMsg_6()  throws Throwable  {
      //caseID:20a2352adc96d17017484599263e6355
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_String: 1.0
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: setMsg
      goodsDetailResponse0.setMsg("1.0");
      
      //Test Result Assert
      assertNull(goodsDetailResponse0.getCode());
  }

  @Test(timeout = 9000)
  public void test_setResult_7()  throws Throwable  {
      //caseID:c4b4bba68ffc3ba5385edfd9c10e03e7
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_GoodsDetailResult: {}
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      //mock goodsDetailResult0
      GoodsDetailResult goodsDetailResult0 = mock(GoodsDetailResult.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: setResult
      goodsDetailResponse0.setResult(goodsDetailResult0);
      
      //Test Result Assert
      assertNull(goodsDetailResponse0.getMsg());
  }

  @Test(timeout = 9000)
  public void test_toString_8()  throws Throwable  {
      //caseID:19f1a7fa3801289ed727a696e895881c
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      //Assert: assertEquals("GoodsDetailResponse(code=null, msg=null, result=null)", method_result);
      
      GoodsDetailResponse goodsDetailResponse0 = new GoodsDetailResponse();
      
      //Call method: toString
      String string0 = goodsDetailResponse0.toString();
      
      //Test Result Assert
      assertEquals("GoodsDetailResponse(code=null, msg=null, result=null)", string0);
  }
}
