/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.nbcb.entity.ResultSpec;
import com.nbcb.entity.Value;
import java.util.LinkedList;
import java.util.List;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ResultSpec_SSTest extends ResultSpec_SSTest_scaffolding {
// allCoveredLines:[7, 12, 16, 20]

  @Test(timeout = 9000)
  public void test_equals_0()  throws Throwable  {
      //caseID:af53cba301e04597ac17f5e2cd192310
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_Object: resultSpec0
      //Assert: assertTrue(method_result);
      
      ResultSpec resultSpec0 = new ResultSpec();
      
      //Call method: equals
      boolean boolean0 = resultSpec0.equals(resultSpec0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_1()  throws Throwable  {
      //caseID:3d8c273dcd78bbd2931b2505f5ee70c0
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_Object: !M]lg
      //Assert: assertFalse(method_result);
      
      ResultSpec resultSpec0 = new ResultSpec();
      
      //Call method: equals
      boolean boolean0 = resultSpec0.equals("!M]lg");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_2()  throws Throwable  {
      //caseID:b12cf4230f291a24a992a892cc1d2c60
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      //Input_0_Object: resultSpec0
      //Assert: assertTrue(method_result);
      
      ResultSpec resultSpec0 = new ResultSpec();
      ResultSpec resultSpec1 = new ResultSpec();
      
      //Call method: equals
      boolean boolean0 = resultSpec1.equals(resultSpec0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_3()  throws Throwable  {
      //caseID:73358d5d3639a11eef518fe1fbbd70d5
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      //Input_0_Object: resultSpec1
      //Assert: assertTrue(method_result);
      
      ResultSpec resultSpec0 = new ResultSpec();
      ResultSpec resultSpec1 = new ResultSpec();
      
      //Call method: equals
      boolean boolean0 = resultSpec0.equals(resultSpec1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_4()  throws Throwable  {
      //caseID:f050e0a7537b581c9b5c449dbd5286c1
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      
      ResultSpec resultSpec0 = new ResultSpec();
      
      //Call method: hashCode
      resultSpec0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setId_5()  throws Throwable  {
      //caseID:3e7a5cec6a7cf02a397443123d4353bc
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_String: 
      
      ResultSpec resultSpec0 = new ResultSpec();
      
      //Call method: setId
      resultSpec0.setId("");
      
      //Test Result Assert
      assertEquals("", resultSpec0.getId());
  }

  @Test(timeout = 9000)
  public void test_setName_6()  throws Throwable  {
      //caseID:84b0360f932fc6fea9f43e03b9c581e3
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_String: , name=
      
      ResultSpec resultSpec0 = new ResultSpec();
      
      //Call method: setName
      resultSpec0.setName(", name=");
      
      //Test Result Assert
      assertEquals(", name=", resultSpec0.getName());
  }

  @Test(timeout = 9000)
  public void test_setValues_7()  throws Throwable  {
      //caseID:3a625023a4ec177bc5fe25f7e072cca5
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7]
      //Input_0_List<Value>: linkedList0
      
      ResultSpec resultSpec0 = new ResultSpec();
      LinkedList<Value> linkedList0 = new LinkedList<Value>();
      
      //Call method: setValues
      resultSpec0.setValues(linkedList0);
      
      //Test Result Assert
      assertNull(resultSpec0.getId());
  }

  @Test(timeout = 9000)
  public void test_toString_8()  throws Throwable  {
      //caseID:79fdf5d1fc86d1db38b01ada52efd94f
      //CoveredLines: [7, 7, 7, 7, 7, 7, 7, 7, 12, 16, 20]
      //Assert: assertEquals("ResultSpec(id=null, name=null, values=null)", method_result);
      
      ResultSpec resultSpec0 = new ResultSpec();
      
      //Call method: toString
      String string0 = resultSpec0.toString();
      
      //Test Result Assert
      assertEquals("ResultSpec(id=null, name=null, values=null)", string0);
  }
}
