/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.nbcb.entity.SimilarProduct;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class SimilarProduct_SSTest extends SimilarProduct_SSTest_scaffolding {
// allCoveredLines:[5, 10, 14, 18, 22, 26, 30, 34]

  @Test(timeout = 9000)
  public void test_equals_00()  throws Throwable  {
      //caseID:385b9ff6220b82ef826dc1b13015fcdf
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_Object: Z(X'u
      //Assert: assertFalse(method_result);
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: equals
      boolean boolean0 = similarProduct0.equals("Z(X'u");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_01()  throws Throwable  {
      //caseID:63b817a7bac899153881cd600b312d71
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_Object: similarProduct0
      //Assert: assertTrue(method_result);
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: equals
      boolean boolean0 = similarProduct0.equals(similarProduct0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_02()  throws Throwable  {
      //caseID:a868eb7a537e2fabaecf4af4ef9113ca
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 14, 18, 22, 26, 30, 34]
      //Input_0_Object: similarProduct1
      //Assert: assertTrue(method_result);
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      SimilarProduct similarProduct1 = new SimilarProduct();
      
      //Call method: equals
      boolean boolean0 = similarProduct0.equals(similarProduct1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_03()  throws Throwable  {
      //caseID:d20a99cd32a31ec245dae7f7584f57ed
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 14, 18, 22, 26, 30, 34]
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: hashCode
      similarProduct0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setDesc_04()  throws Throwable  {
      //caseID:a78e516e923c6e0a30818fc4bc948e98
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_String: ']YWIb~Ml%(?
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: setDesc
      similarProduct0.setDesc("']YWIb~Ml%(?");
      
      //Test Result Assert
      assertNull(similarProduct0.getPicture());
  }

  @Test(timeout = 9000)
  public void test_setDiscount_05()  throws Throwable  {
      //caseID:4b2425a9bdea698e9dc69f8482db55b4
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_Object: SimilarProduct(desc=
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: setDiscount
      similarProduct0.setDiscount("SimilarProduct(desc=");
      
      //Test Result Assert
      assertNull(similarProduct0.getPicture());
  }

  @Test(timeout = 9000)
  public void test_setId_06()  throws Throwable  {
      //caseID:bde74013cb57973b24c052f0210252b4
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_String: 1
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: setId
      similarProduct0.setId("1");
      
      //Test Result Assert
      assertNull(similarProduct0.getName());
  }

  @Test(timeout = 9000)
  public void test_setName_07()  throws Throwable  {
      //caseID:98429b1d08eb693f36d9cd53b17e0efc
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_String: SimilarProduct(desc=
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: setName
      similarProduct0.setName("SimilarProduct(desc=");
      
      //Test Result Assert
      assertEquals(0L, similarProduct0.getOrderNum());
  }

  @Test(timeout = 9000)
  public void test_setOrderNum_08()  throws Throwable  {
      //caseID:fbf2d69fe1cf684b8a8191ee96a38b02
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_long: 1
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: setOrderNum
      similarProduct0.setOrderNum(1L);
      
      //Test Result Assert
      assertNull(similarProduct0.getId());
  }

  @Test(timeout = 9000)
  public void test_setPicture_09()  throws Throwable  {
      //caseID:18baadd71ac8107c9453c222c032edb3
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_String: 1
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: setPicture
      similarProduct0.setPicture("1");
      
      //Test Result Assert
      assertNull(similarProduct0.getId());
  }

  @Test(timeout = 9000)
  public void test_setPrice_10()  throws Throwable  {
      //caseID:3479862081764b695ddb2e8421865535
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
      //Input_0_String: , orderNum=
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: setPrice
      similarProduct0.setPrice(", orderNum=");
      
      //Test Result Assert
      assertNull(similarProduct0.getPicture());
  }

  @Test(timeout = 9000)
  public void test_toString_11()  throws Throwable  {
      //caseID:d9fe0f94faf6f1cb38a8b53be04df901
      //CoveredLines: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 10, 14, 18, 22, 26, 30, 34]
      //Assert: assertEquals("SimilarProduct(desc=null, discount=null, id=null, name=null, orderNum=0, picture=null, price=null)", method_result);
      
      SimilarProduct similarProduct0 = new SimilarProduct();
      
      //Call method: toString
      String string0 = similarProduct0.toString();
      
      //Test Result Assert
      assertEquals("SimilarProduct(desc=null, discount=null, id=null, name=null, orderNum=0, picture=null, price=null)", string0);
  }
}
