/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.nbcb.utils.MD5Util;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class MD5Util_SSTest extends MD5Util_SSTest_scaffolding {
// allCoveredLines:[12, 15, 27, 28, 38, 39, 43, 44, 45, 49, 50, 51]

  @Test(timeout = 9000)
  public void test_inputPassToDBPass_0()  throws Throwable  {
      //caseID:a19fac1e6842e4555eca5cdf2853f8d3
      //CoveredLines: [12, 15, 27, 28, 38, 39, 43, 44, 45]
      //Input_0_String: uL\"#$c}3^b8S08
      //Input_1_String: 123456
      //Assert: assertEquals("a803471add7ea6908ccb3b1360ebe13f", method_result);
      
      MD5Util mD5Util0 = new MD5Util();
      
      //Call method: inputPassToDBPass
      String string0 = MD5Util.inputPassToDBPass("uL\"#$c}3^b8S08", "123456");
      
      //Test Result Assert
      assertEquals("a803471add7ea6908ccb3b1360ebe13f", string0);
  }

  @Test(timeout = 9000)
  public void test_main_1()  throws Throwable  {
      //caseID:52a1fada4a3c6c880752db310ac580a5
      //CoveredLines: [15, 27, 28, 38, 39, 43, 44, 45, 49, 50, 51]
      //Input_0_String[]: stringArray0
      
      String[] stringArray0 = new String[1];
      
      //Call method: main
      MD5Util.main(stringArray0);
      
      //Test Result Assert
      assertEquals(1, stringArray0.length);
  }
}
