/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.constant;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.nbcb.constant.ShopCode;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ShopCode_SSTest extends ShopCode_SSTest_scaffolding {
// allCoveredLines:[84, 88, 92, 96, 97, 110]

  @Test(timeout = 9000)
  public void test_getCode_0()  throws Throwable  {
      //caseID:d200ae89773b1020efc87c131711c485
      //CoveredLines: [88]
      
      ShopCode shopCode0 = ShopCode.SHOP_USER_MONEY_REDUCE_FAIL;
      
      //Call method: getCode
      shopCode0.getCode();
  }

  @Test(timeout = 9000)
  public void test_getMessage_1()  throws Throwable  {
      //caseID:c03368f603f204ab891a659e0f13719e
      //CoveredLines: [92]
      
      ShopCode shopCode0 = ShopCode.SHOP_REDUCE_GOODS_NUM_EMPTY;
      
      //Call method: getMessage
      shopCode0.getMessage();
  }

  @Test(timeout = 9000)
  public void test_getSuccess_2()  throws Throwable  {
      //caseID:99a5a43d46e7a3de093deeaf32dabe6d
      //CoveredLines: [84]
      
      ShopCode shopCode0 = ShopCode.SHOP_GOODS_NUM_NOT_ENOUGH;
      
      //Call method: getSuccess
      shopCode0.getSuccess();
  }

  @Test(timeout = 9000)
  public void test_setMessage_3()  throws Throwable  {
      //caseID:98a2b3531b9315f460ef3a74439ce2cd
      //CoveredLines: [96, 97]
      //Input_0_String: 1
      
      ShopCode shopCode0 = ShopCode.SHOP_ORDER_INVALID;
      
      //Call method: setMessage
      shopCode0.setMessage("1");
  }

  @Test(timeout = 9000)
  public void test_toString_4()  throws Throwable  {
      //caseID:0293a79688fe6456a73abaa6796367e4
      //CoveredLines: [110]
      
      ShopCode shopCode0 = ShopCode.SHOP_USER_NO_EXIST;
      
      //Call method: toString
      shopCode0.toString();
  }
}
