/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.mq;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.nbcb.mq.CallbackConsumerMQListener;
import org.junit.runner.RunWith;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class CallbackConsumerMQListener_SSTest extends CallbackConsumerMQListener_SSTest_scaffolding {
// allCoveredLines:[33, 63, 64, 65, 66, 67, 68, 69, 70, 75, 77, 78, 79]

  @Test(timeout = 9000)
  public void test_getCallbackRocketMQConsumer_0()  throws Throwable  {
      //caseID:7d7b9eacb77c9be4e71471df8323f58a
      //CoveredLines: [33, 63, 64, 65, 66, 67, 68, 69, 70, 75, 77, 78, 79]
      
      CallbackConsumerMQListener callbackConsumerMQListener0 = new CallbackConsumerMQListener();
      
      PrivateAccess.setVariable((Class<?>) CallbackConsumerMQListener.class, callbackConsumerMQListener0, "callbackTopic", (Object) "-1354573786");
      
      //Call method: getCallbackRocketMQConsumer
      try { 
        callbackConsumerMQListener0.getCallbackRocketMQConsumer();
      } catch(Throwable e) {
         verifyException("org.apache.rocketmq.client.Validators", e);
         assertEquals("org.apache.rocketmq.client.exception.MQClientException", e.getClass().getName());
         assertEquals("the specified group is blank\nFor more information, please visit the url, http://rocketmq.apache.org/docs/faq/", e.getMessage());
      }
  }
}
