/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.mq;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.nbcb.mq.SeckillConsumerGoodsNumMQListener;
import org.junit.runner.RunWith;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class SeckillConsumerGoodsNumMQListener_SSTest extends SeckillConsumerGoodsNumMQListener_SSTest_scaffolding {
// allCoveredLines:[27, 47, 48, 49, 50, 51, 52, 53, 54, 59]

  @Test(timeout = 9000)
  public void test_getSeckillRocketMQConsumer_0()  throws Throwable  {
      //caseID:79286de059079a64a891b1ce0cf069d2
      //CoveredLines: [27, 47, 48, 49, 50, 51, 52, 53, 54, 59]
      
      SeckillConsumerGoodsNumMQListener seckillConsumerGoodsNumMQListener0 = new SeckillConsumerGoodsNumMQListener();
      
      PrivateAccess.setVariable((Class<?>) SeckillConsumerGoodsNumMQListener.class, seckillConsumerGoodsNumMQListener0, "topic", (Object) "1.0");
      
      //Call method: getSeckillRocketMQConsumer
      try { 
        seckillConsumerGoodsNumMQListener0.getSeckillRocketMQConsumer();
      } catch(Throwable e) {
         verifyException("org.apache.rocketmq.client.Validators", e);
         assertEquals("org.apache.rocketmq.client.exception.MQClientException", e.getClass().getName());
         assertEquals("the specified group is blank\nFor more information, please visit the url, http://rocketmq.apache.org/docs/faq/", e.getMessage());
      }
  }
}
