server:
  port: 8082
spring:
  application:
    name: dubbo-goods-provider
  datasource:
    name: shop
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      id: dubbo-goods-provider
      name: dubbo-goods-provider
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181;zookeeper://127.0.0.1:2182;zookeeper://127.0.0.1:2183
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20881
#    scan: com.dubboProvide.dubboProvide.service  #服务暴露与发现消费所在的package
mybatis:
  type-aliases-package: com.nbcb.pojo
  mapper-locations: classpath:/com.nbcb.mapper/*.xml
#RocketMQ配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: orderProducerGroup
    send-message-timeout: 50000
# 自定义消息参数
mq:
  order:
    confirm:
      topic: orderConfirmTopic
      consumer:
        groupname: order_confirm_group
        callback:
          topic: orderConfirmCallbackTopic
          tag: order_confirm_callback
          sourcecode: goods
    consumer:
      group:
        name: order_orderTopic_cancel_group
    topic: orderTopic
  goods:
    consumer:
      group:
        name: goods_goodsTopic_reduce_group
    topic: goodsNumTopic
    tag:
      reduce: reduce_goods_num