/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.nbcb.CouponServiceApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class CouponServiceApplication_SSTest extends CouponServiceApplication_SSTest_scaffolding {
// allCoveredLines:[9]

  @Test(timeout = 9000)
  public void test_setCurrentTimeMillis_0()  throws Throwable  {
      //caseID:6cec7a5c4e3d94a9103a00fe42f046ab
      //CoveredLines: [9]
      
      CouponServiceApplication couponServiceApplication0 = new CouponServiceApplication();
  }
}
