/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.pojo;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.nbcb.pojo.ShopOrderMqStatusLogExample;
import java.util.LinkedList;
import java.util.List;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ShopOrderMqStatusLogExample_SSTest extends ShopOrderMqStatusLogExample_SSTest_scaffolding {
// allCoveredLines:[13, 14, 15, 18, 19, 22, 26, 27, 30, 34, 38, 39, 42, 43, 44, 48, 49, 50, 52, 56, 57, 61, 62, 63, 64, 70, 71, 72, 561, 562]

  @Test(timeout = 9000)
  public void test_clear_0()  throws Throwable  {
      //caseID:f313601641c9e556c393c42bf6239d25
      //CoveredLines: [13, 14, 15, 61, 62, 63, 64]
      
      ShopOrderMqStatusLogExample shopOrderMqStatusLogExample0 = new ShopOrderMqStatusLogExample();
      
      //Call method: clear
      shopOrderMqStatusLogExample0.clear();
      
      //Test Result Assert
      assertFalse(shopOrderMqStatusLogExample0.isDistinct());
  }

  @Test(timeout = 9000)
  public void test_createCriteria_1()  throws Throwable  {
      //caseID:aeb615b716261f9042ea8a150a70448e
      //CoveredLines: [13, 14, 15, 48, 49, 52, 56, 57, 70, 71, 72, 561, 562]
      //Assert: assertFalse(method_result.equals((Object)shopOrderMqStatusLogExample_Criteria0));
      
      ShopOrderMqStatusLogExample shopOrderMqStatusLogExample0 = new ShopOrderMqStatusLogExample();
      LinkedList<ShopOrderMqStatusLogExample.Criteria> linkedList0 = new LinkedList<ShopOrderMqStatusLogExample.Criteria>();
      //mock shopOrderMqStatusLogExample_Criteria0
      ShopOrderMqStatusLogExample.Criteria shopOrderMqStatusLogExample_Criteria0 = mock(ShopOrderMqStatusLogExample.Criteria.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      linkedList0.add(shopOrderMqStatusLogExample_Criteria0);
      
      PrivateAccess.setVariable((Class<?>) ShopOrderMqStatusLogExample.class, shopOrderMqStatusLogExample0, "oredCriteria", (Object) linkedList0);
      
      //Call method: createCriteria
      ShopOrderMqStatusLogExample.Criteria shopOrderMqStatusLogExample_Criteria1 = shopOrderMqStatusLogExample0.createCriteria();
      
      //Test Result Assert
      assertFalse(shopOrderMqStatusLogExample_Criteria1.equals((Object)shopOrderMqStatusLogExample_Criteria0));
  }

  @Test(timeout = 9000)
  public void test_createCriteria_2()  throws Throwable  {
      //caseID:5c209e2fc5416ff4bb57b11756f326b8
      //CoveredLines: [13, 14, 15, 48, 49, 50, 52, 56, 57, 70, 71, 72, 561, 562]
      //Assert: assertNotNull(method_result);
      
      ShopOrderMqStatusLogExample shopOrderMqStatusLogExample0 = new ShopOrderMqStatusLogExample();
      
      //Call method: createCriteria
      ShopOrderMqStatusLogExample.Criteria shopOrderMqStatusLogExample_Criteria0 = shopOrderMqStatusLogExample0.createCriteria();
      
      //Test Result Assert
      assertNotNull(shopOrderMqStatusLogExample_Criteria0);
  }

  @Test(timeout = 9000)
  public void test_getOrderByClause_3()  throws Throwable  {
      //caseID:789402b87f8642cb00dc411188375d4e
      //CoveredLines: [13, 14, 15, 22]
      //Assert: assertNull(method_result);
      
      ShopOrderMqStatusLogExample shopOrderMqStatusLogExample0 = new ShopOrderMqStatusLogExample();
      
      //Call method: getOrderByClause
      String string0 = shopOrderMqStatusLogExample0.getOrderByClause();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 9000)
  public void test_getOredCriteria_4()  throws Throwable  {
      //caseID:f91d906881b306e72c471b13205ed040
      //CoveredLines: [13, 14, 15, 34]
      //Assert: assertTrue(method_result.isEmpty());
      
      ShopOrderMqStatusLogExample shopOrderMqStatusLogExample0 = new ShopOrderMqStatusLogExample();
      
      //Call method: getOredCriteria
      List<ShopOrderMqStatusLogExample.Criteria> list0 = shopOrderMqStatusLogExample0.getOredCriteria();
      
      //Test Result Assert
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 9000)
  public void test_isDistinct_5()  throws Throwable  {
      //caseID:e722449b4a7a18363c11d5b566a5757d
      //CoveredLines: [13, 14, 15, 30]
      //Assert: assertFalse(method_result);
      
      ShopOrderMqStatusLogExample shopOrderMqStatusLogExample0 = new ShopOrderMqStatusLogExample();
      
      //Call method: isDistinct
      boolean boolean0 = shopOrderMqStatusLogExample0.isDistinct();
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_or_6()  throws Throwable  {
      //caseID:c78b47cab6eafa45e295c8ce1cef4936
      //CoveredLines: [13, 14, 15, 38, 39]
      //Input_0_ShopOrderMqStatusLogExample.Criteria: {}
      
      ShopOrderMqStatusLogExample shopOrderMqStatusLogExample0 = new ShopOrderMqStatusLogExample();
      //mock shopOrderMqStatusLogExample_Criteria0
      ShopOrderMqStatusLogExample.Criteria shopOrderMqStatusLogExample_Criteria0 = mock(ShopOrderMqStatusLogExample.Criteria.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: or
      shopOrderMqStatusLogExample0.or(shopOrderMqStatusLogExample_Criteria0);
      
      //Test Result Assert
      assertFalse(shopOrderMqStatusLogExample0.isDistinct());
  }

  @Test(timeout = 9000)
  public void test_or_7()  throws Throwable  {
      //caseID:3a2354aec8472aece02a782a1d17c8c4
      //CoveredLines: [13, 14, 15, 42, 43, 44, 56, 57, 70, 71, 72, 561, 562]
      //Assert: assertNotNull(method_result);
      
      ShopOrderMqStatusLogExample shopOrderMqStatusLogExample0 = new ShopOrderMqStatusLogExample();
      
      //Call method: or
      ShopOrderMqStatusLogExample.Criteria shopOrderMqStatusLogExample_Criteria0 = shopOrderMqStatusLogExample0.or();
      
      //Test Result Assert
      assertNotNull(shopOrderMqStatusLogExample_Criteria0);
  }

  @Test(timeout = 9000)
  public void test_setDistinct_8()  throws Throwable  {
      //caseID:7d802a4e888772d9236c25bcc6994275
      //CoveredLines: [13, 14, 15, 26, 27]
      //Input_0_boolean: true
      
      ShopOrderMqStatusLogExample shopOrderMqStatusLogExample0 = new ShopOrderMqStatusLogExample();
      
      //Call method: setDistinct
      shopOrderMqStatusLogExample0.setDistinct(true);
      
      //Test Result Assert
      assertNull(shopOrderMqStatusLogExample0.getOrderByClause());
  }

  @Test(timeout = 9000)
  public void test_setOrderByClause_9()  throws Throwable  {
      //caseID:1ef98972a066a964cdff13a864daaa52
      //CoveredLines: [13, 14, 15, 18, 19]
      //Input_0_String: 0
      
      ShopOrderMqStatusLogExample shopOrderMqStatusLogExample0 = new ShopOrderMqStatusLogExample();
      
      //Call method: setOrderByClause
      shopOrderMqStatusLogExample0.setOrderByClause("0");
      
      //Test Result Assert
      assertEquals("0", shopOrderMqStatusLogExample0.getOrderByClause());
  }
}
