/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.pojo;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.nbcb.pojo.ShopCoupon;
import java.math.BigDecimal;
import java.util.Date;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ShopCoupon_SSTest extends ShopCoupon_SSTest_scaffolding {
// allCoveredLines:[9, 11, 13, 15, 17, 19, 21]

  @Test(timeout = 9000)
  public void test_equals_00()  throws Throwable  {
      //caseID:36580e08f80baa38dd1d528b3da10f21
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
      //Input_0_Object: shopCoupon0
      //Assert: assertTrue(method_result);
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      
      //Call method: equals
      boolean boolean0 = shopCoupon0.equals(shopCoupon0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_01()  throws Throwable  {
      //caseID:18bf35864f94d2b3c658d844b2c6ea8b
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
      //Input_0_Object: 300
      //Assert: assertFalse(method_result);
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      Integer integer0 = new Integer(300);
      
      //Call method: equals
      boolean boolean0 = shopCoupon0.equals(integer0);
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_02()  throws Throwable  {
      //caseID:d977b14f75aee37929c613753c18fd9f
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 11, 13, 15, 17, 19, 21]
      //Input_0_Object: shopCoupon1
      //Assert: assertTrue(method_result);
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      ShopCoupon shopCoupon1 = new ShopCoupon();
      
      //Call method: equals
      boolean boolean0 = shopCoupon0.equals(shopCoupon1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_equals_03()  throws Throwable  {
      //caseID:8ffa9d8d0134b16d9cace0288e49c9f1
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 11, 13, 15, 17, 19, 21]
      //Input_0_Object: shopCoupon0
      //Assert: assertTrue(method_result);
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      ShopCoupon shopCoupon1 = new ShopCoupon();
      
      //Call method: equals
      boolean boolean0 = shopCoupon1.equals(shopCoupon0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 9000)
  public void test_hashCode_04()  throws Throwable  {
      //caseID:bc627ae78c05f8c7cdd3aeac1cf5bf25
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 11, 13, 15, 17, 19, 21]
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      
      //Call method: hashCode
      shopCoupon0.hashCode();
  }

  @Test(timeout = 9000)
  public void test_setCouponId_05()  throws Throwable  {
      //caseID:7a668612c707e749470fc0389ff65c8e
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
      //Input_0_Long: 0L
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      Long long0 = new Long(0L);
      
      //Call method: setCouponId
      shopCoupon0.setCouponId(long0);
      
      //Test Result Assert
      assertNull(shopCoupon0.getOrderId());
  }

  @Test(timeout = 9000)
  public void test_setCouponPrice_06()  throws Throwable  {
      //caseID:a7a329cdd62012e1a1e467c1c6ce7969
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
      //Input_0_BigDecimal: BigDecimal.TEN
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      
      //Call method: setCouponPrice
      shopCoupon0.setCouponPrice(bigDecimal0);
      
      //Test Result Assert
      assertNull(shopCoupon0.getOrderId());
  }

  @Test(timeout = 9000)
  public void test_setIsUsed_07()  throws Throwable  {
      //caseID:0f377ed44f2e36e8a94362c8888ede99
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
      //Input_0_Integer: 0
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      Integer integer0 = new Integer(0);
      
      //Call method: setIsUsed
      shopCoupon0.setIsUsed(integer0);
      
      //Test Result Assert
      assertNull(shopCoupon0.getCouponId());
  }

  @Test(timeout = 9000)
  public void test_setOrderId_08()  throws Throwable  {
      //caseID:528b40eaad8e66ec3333a319d5618f77
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
      //Input_0_Long: 0L
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      Long long0 = new Long(0L);
      
      //Call method: setOrderId
      shopCoupon0.setOrderId(long0);
      
      //Test Result Assert
      assertNull(shopCoupon0.getIsUsed());
  }

  @Test(timeout = 9000)
  public void test_setUsedTime_09()  throws Throwable  {
      //caseID:4fec3a31507d60b561a546d9ef93172f
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
      //Input_0_Date: {}
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      //mock date0
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: setUsedTime
      shopCoupon0.setUsedTime(date0);
      
      //Test Result Assert
      assertNull(shopCoupon0.getUserId());
  }

  @Test(timeout = 9000)
  public void test_setUserId_10()  throws Throwable  {
      //caseID:53263e09d148078eefc9a87e500ae69b
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]
      //Input_0_Long: 1559L
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      Long long0 = new Long(1559L);
      
      //Call method: setUserId
      shopCoupon0.setUserId(long0);
      
      //Test Result Assert
      assertNull(shopCoupon0.getOrderId());
  }

  @Test(timeout = 9000)
  public void test_toString_11()  throws Throwable  {
      //caseID:d1620568d499bcdcc0ef24ee9692363c
      //CoveredLines: [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 11, 13, 15, 17, 19, 21]
      //Assert: assertEquals("ShopCoupon(couponId=null, couponPrice=null, userId=null, orderId=null, isUsed=null, usedTime=null)", method_result);
      
      ShopCoupon shopCoupon0 = new ShopCoupon();
      
      //Call method: toString
      String string0 = shopCoupon0.toString();
      
      //Test Result Assert
      assertEquals("ShopCoupon(couponId=null, couponPrice=null, userId=null, orderId=null, isUsed=null, usedTime=null)", string0);
  }
}
