/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.pojo;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.nbcb.pojo.ShopUserMoneyLogExample;
import java.util.LinkedList;
import java.util.List;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ShopUserMoneyLogExample_SSTest extends ShopUserMoneyLogExample_SSTest_scaffolding {
// allCoveredLines:[16, 17, 18, 21, 22, 25, 29, 30, 33, 37, 41, 42, 45, 46, 47, 51, 52, 53, 55, 59, 60, 64, 65, 66, 67, 73, 74, 75, 414, 415]

  @Test(timeout = 9000)
  public void test_clear_0()  throws Throwable  {
      //caseID:bee80659bfbb59472e028cb2aa80587b
      //CoveredLines: [16, 17, 18, 64, 65, 66, 67]
      
      ShopUserMoneyLogExample shopUserMoneyLogExample0 = new ShopUserMoneyLogExample();
      
      //Call method: clear
      shopUserMoneyLogExample0.clear();
      
      //Test Result Assert
      assertFalse(shopUserMoneyLogExample0.isDistinct());
  }

  @Test(timeout = 9000)
  public void test_createCriteria_1()  throws Throwable  {
      //caseID:74da16a2e198e6aa769d9ac2c8f75b44
      //CoveredLines: [16, 17, 18, 51, 52, 55, 59, 60, 73, 74, 75, 414, 415]
      //Assert: assertFalse(method_result.equals((Object)shopUserMoneyLogExample_Criteria0));
      
      ShopUserMoneyLogExample shopUserMoneyLogExample0 = new ShopUserMoneyLogExample();
      LinkedList<ShopUserMoneyLogExample.Criteria> linkedList0 = new LinkedList<ShopUserMoneyLogExample.Criteria>();
      //mock shopUserMoneyLogExample_Criteria0
      ShopUserMoneyLogExample.Criteria shopUserMoneyLogExample_Criteria0 = mock(ShopUserMoneyLogExample.Criteria.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      linkedList0.add(shopUserMoneyLogExample_Criteria0);
      
      PrivateAccess.setVariable((Class<?>) ShopUserMoneyLogExample.class, shopUserMoneyLogExample0, "oredCriteria", (Object) linkedList0);
      
      //Call method: createCriteria
      ShopUserMoneyLogExample.Criteria shopUserMoneyLogExample_Criteria1 = shopUserMoneyLogExample0.createCriteria();
      
      //Test Result Assert
      assertFalse(shopUserMoneyLogExample_Criteria1.equals((Object)shopUserMoneyLogExample_Criteria0));
  }

  @Test(timeout = 9000)
  public void test_createCriteria_2()  throws Throwable  {
      //caseID:117827d62307232f0d0c57a5ec26a75d
      //CoveredLines: [16, 17, 18, 51, 52, 53, 55, 59, 60, 73, 74, 75, 414, 415]
      //Assert: assertNotNull(method_result);
      
      ShopUserMoneyLogExample shopUserMoneyLogExample0 = new ShopUserMoneyLogExample();
      
      //Call method: createCriteria
      ShopUserMoneyLogExample.Criteria shopUserMoneyLogExample_Criteria0 = shopUserMoneyLogExample0.createCriteria();
      
      //Test Result Assert
      assertNotNull(shopUserMoneyLogExample_Criteria0);
  }

  @Test(timeout = 9000)
  public void test_getOrderByClause_3()  throws Throwable  {
      //caseID:83af755de7357710ebaf38b7f081ef7a
      //CoveredLines: [16, 17, 18, 25]
      //Assert: assertNull(method_result);
      
      ShopUserMoneyLogExample shopUserMoneyLogExample0 = new ShopUserMoneyLogExample();
      
      //Call method: getOrderByClause
      String string0 = shopUserMoneyLogExample0.getOrderByClause();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 9000)
  public void test_getOredCriteria_4()  throws Throwable  {
      //caseID:123b3585c061d00295a1e8034874d2ec
      //CoveredLines: [16, 17, 18, 37]
      //Assert: assertEquals(0, method_result.size());
      
      ShopUserMoneyLogExample shopUserMoneyLogExample0 = new ShopUserMoneyLogExample();
      
      //Call method: getOredCriteria
      List<ShopUserMoneyLogExample.Criteria> list0 = shopUserMoneyLogExample0.getOredCriteria();
      
      //Test Result Assert
      assertEquals(0, list0.size());
  }

  @Test(timeout = 9000)
  public void test_isDistinct_5()  throws Throwable  {
      //caseID:6ff321d470d82df94fa97f54a94ffa3f
      //CoveredLines: [16, 17, 18, 33]
      //Assert: assertFalse(method_result);
      
      ShopUserMoneyLogExample shopUserMoneyLogExample0 = new ShopUserMoneyLogExample();
      
      //Call method: isDistinct
      boolean boolean0 = shopUserMoneyLogExample0.isDistinct();
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 9000)
  public void test_or_6()  throws Throwable  {
      //caseID:8d60ed3ba4d8700278eae984ac720e6e
      //CoveredLines: [16, 17, 18, 41, 42]
      //Input_0_ShopUserMoneyLogExample.Criteria: {}
      
      ShopUserMoneyLogExample shopUserMoneyLogExample0 = new ShopUserMoneyLogExample();
      //mock shopUserMoneyLogExample_Criteria0
      ShopUserMoneyLogExample.Criteria shopUserMoneyLogExample_Criteria0 = mock(ShopUserMoneyLogExample.Criteria.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: or
      shopUserMoneyLogExample0.or(shopUserMoneyLogExample_Criteria0);
      
      //Test Result Assert
      assertNull(shopUserMoneyLogExample0.getOrderByClause());
  }

  @Test(timeout = 9000)
  public void test_or_7()  throws Throwable  {
      //caseID:6063344f9509b5423438f051aa7c0db2
      //CoveredLines: [16, 17, 18, 45, 46, 47, 59, 60, 73, 74, 75, 414, 415]
      //Assert: assertNotNull(method_result);
      
      ShopUserMoneyLogExample shopUserMoneyLogExample0 = new ShopUserMoneyLogExample();
      
      //Call method: or
      ShopUserMoneyLogExample.Criteria shopUserMoneyLogExample_Criteria0 = shopUserMoneyLogExample0.or();
      
      //Test Result Assert
      assertNotNull(shopUserMoneyLogExample_Criteria0);
  }

  @Test(timeout = 9000)
  public void test_setDistinct_8()  throws Throwable  {
      //caseID:44a556ce582cd1079cb59061181ca8bb
      //CoveredLines: [16, 17, 18, 29, 30]
      //Input_0_boolean: true
      
      ShopUserMoneyLogExample shopUserMoneyLogExample0 = new ShopUserMoneyLogExample();
      
      //Call method: setDistinct
      shopUserMoneyLogExample0.setDistinct(true);
      
      //Test Result Assert
      assertNull(shopUserMoneyLogExample0.getOrderByClause());
  }

  @Test(timeout = 9000)
  public void test_setOrderByClause_9()  throws Throwable  {
      //caseID:f3c017f0cd6434bb34268f3907c43ed6
      //CoveredLines: [16, 17, 18, 21, 22]
      //Input_0_String: 2
      
      ShopUserMoneyLogExample shopUserMoneyLogExample0 = new ShopUserMoneyLogExample();
      
      //Call method: setOrderByClause
      shopUserMoneyLogExample0.setOrderByClause("2");
      
      //Test Result Assert
      assertFalse(shopUserMoneyLogExample0.isDistinct());
  }
}
