/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.pojo;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.nbcb.pojo.ShopOrderMqStatusLog;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ShopOrderMqStatusLog_SSTest extends ShopOrderMqStatusLog_SSTest_scaffolding {
// allCoveredLines:[3, 19, 23, 24, 27, 31, 32, 35, 39, 40, 43, 47, 48, 51, 55, 56, 59, 63, 64, 67, 71, 72]

  @Test(timeout = 9000)
  public void test_getCouponResult_00()  throws Throwable  {
      //caseID:06e21b73de6a3b297d742d4d30097b47
      //CoveredLines: [3, 51]
      //Assert: assertNull(method_result);
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: getCouponResult
      String string0 = shopOrderMqStatusLog0.getCouponResult();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 9000)
  public void test_getCouponStatus_01()  throws Throwable  {
      //caseID:c44891f9c403daade93c243aac254cff
      //CoveredLines: [3, 43]
      //Assert: assertNull(method_result);
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: getCouponStatus
      Integer integer0 = shopOrderMqStatusLog0.getCouponStatus();
      
      //Test Result Assert
      assertNull(integer0);
  }

  @Test(timeout = 9000)
  public void test_getGoodsResult_02()  throws Throwable  {
      //caseID:8055157fa2dcf0ff4c7c6929f5ad3834
      //CoveredLines: [3, 35]
      //Assert: assertNull(method_result);
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: getGoodsResult
      String string0 = shopOrderMqStatusLog0.getGoodsResult();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 9000)
  public void test_getGoodsStatus_03()  throws Throwable  {
      //caseID:c53877d8b029a6567d125abae6a47b37
      //CoveredLines: [3, 27]
      //Assert: assertNull(method_result);
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: getGoodsStatus
      Integer integer0 = shopOrderMqStatusLog0.getGoodsStatus();
      
      //Test Result Assert
      assertNull(integer0);
  }

  @Test(timeout = 9000)
  public void test_getOrderId_04()  throws Throwable  {
      //caseID:0dd311b327284264b00b26ff9b7da944
      //CoveredLines: [3, 19]
      //Assert: assertNull(method_result);
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: getOrderId
      Long long0 = shopOrderMqStatusLog0.getOrderId();
      
      //Test Result Assert
      assertNull(long0);
  }

  @Test(timeout = 9000)
  public void test_getUserMoneyStatus_05()  throws Throwable  {
      //caseID:efc16d14f6caf195f7c64481d03910b6
      //CoveredLines: [3, 59]
      //Assert: assertNull(method_result);
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: getUserMoneyStatus
      Integer integer0 = shopOrderMqStatusLog0.getUserMoneyStatus();
      
      //Test Result Assert
      assertNull(integer0);
  }

  @Test(timeout = 9000)
  public void test_getUserResult_06()  throws Throwable  {
      //caseID:7195980361f162fddfd43659d134a1ec
      //CoveredLines: [3, 67]
      //Assert: assertNull(method_result);
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: getUserResult
      String string0 = shopOrderMqStatusLog0.getUserResult();
      
      //Test Result Assert
      assertNull(string0);
  }

  @Test(timeout = 9000)
  public void test_setCouponResult_07()  throws Throwable  {
      //caseID:e6e1b47a8fecbc1caaf594dca440aee9
      //CoveredLines: [3, 55, 56]
      //Input_0_String: null
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: setCouponResult
      shopOrderMqStatusLog0.setCouponResult((String) null);
      
      //Test Result Assert
      assertNull(shopOrderMqStatusLog0.getGoodsStatus());
  }

  @Test(timeout = 9000)
  public void test_setCouponResult_08()  throws Throwable  {
      //caseID:8e2cb8a390791a703d82e6cf31225a82
      //CoveredLines: [3, 55, 56]
      //Input_0_String: 170
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: setCouponResult
      shopOrderMqStatusLog0.setCouponResult("170");
      
      //Test Result Assert
      assertEquals("170", shopOrderMqStatusLog0.getCouponResult());
  }

  @Test(timeout = 9000)
  public void test_setCouponStatus_09()  throws Throwable  {
      //caseID:0ad3b54b5224c344891f8b58a0d34175
      //CoveredLines: [3, 47, 48]
      //Input_0_Integer: 1
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      Integer integer0 = new Integer(1);
      
      //Call method: setCouponStatus
      shopOrderMqStatusLog0.setCouponStatus(integer0);
      
      //Test Result Assert
      assertNull(shopOrderMqStatusLog0.getUserMoneyStatus());
  }

  @Test(timeout = 9000)
  public void test_setGoodsResult_10()  throws Throwable  {
      //caseID:d2eac5eb8e59817263c504925dc9d777
      //CoveredLines: [3, 39, 40]
      //Input_0_String: null
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: setGoodsResult
      shopOrderMqStatusLog0.setGoodsResult((String) null);
      
      //Test Result Assert
      assertNull(shopOrderMqStatusLog0.getOrderId());
  }

  @Test(timeout = 9000)
  public void test_setGoodsResult_11()  throws Throwable  {
      //caseID:4ed7a1ff31009e86876c0c9013902bdb
      //CoveredLines: [3, 39, 40]
      //Input_0_String: 1
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: setGoodsResult
      shopOrderMqStatusLog0.setGoodsResult("1");
      
      //Test Result Assert
      assertEquals("1", shopOrderMqStatusLog0.getGoodsResult());
  }

  @Test(timeout = 9000)
  public void test_setGoodsStatus_12()  throws Throwable  {
      //caseID:918549683258fa19fb4a6d80635e40d1
      //CoveredLines: [3, 31, 32]
      //Input_0_Integer: 1
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      Integer integer0 = new Integer(1);
      
      //Call method: setGoodsStatus
      shopOrderMqStatusLog0.setGoodsStatus(integer0);
      
      //Test Result Assert
      assertNull(shopOrderMqStatusLog0.getCouponStatus());
  }

  @Test(timeout = 9000)
  public void test_setOrderId_13()  throws Throwable  {
      //caseID:e410449dffdf385a474f8459325ee7dd
      //CoveredLines: [3, 23, 24]
      //Input_0_Long: 1
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      Long long0 = new Long(1);
      
      //Call method: setOrderId
      shopOrderMqStatusLog0.setOrderId(long0);
      
      //Test Result Assert
      assertNull(shopOrderMqStatusLog0.getCouponResult());
  }

  @Test(timeout = 9000)
  public void test_setUserMoneyStatus_14()  throws Throwable  {
      //caseID:8d07b4c47308641631c2d58fe31d835c
      //CoveredLines: [3, 63, 64]
      //Input_0_Integer: 36
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      Integer integer0 = new Integer(36);
      
      //Call method: setUserMoneyStatus
      shopOrderMqStatusLog0.setUserMoneyStatus(integer0);
      
      //Test Result Assert
      assertNull(shopOrderMqStatusLog0.getCouponStatus());
  }

  @Test(timeout = 9000)
  public void test_setUserResult_15()  throws Throwable  {
      //caseID:7535cab33716d73690fdab143f6db23d
      //CoveredLines: [3, 71, 72]
      //Input_0_String: null
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: setUserResult
      shopOrderMqStatusLog0.setUserResult((String) null);
      
      //Test Result Assert
      assertNull(shopOrderMqStatusLog0.getUserResult());
  }

  @Test(timeout = 9000)
  public void test_setUserResult_16()  throws Throwable  {
      //caseID:d3314dc8da7a1457390bc13e22526daf
      //CoveredLines: [3, 71, 72]
      //Input_0_String: 1
      
      ShopOrderMqStatusLog shopOrderMqStatusLog0 = new ShopOrderMqStatusLog();
      
      //Call method: setUserResult
      shopOrderMqStatusLog0.setUserResult("1");
      
      //Test Result Assert
      assertEquals("1", shopOrderMqStatusLog0.getUserResult());
  }
}
