/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.nbcb.pojo;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.nbcb.pojo.ShopUserMoneyLogKey;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class ShopUserMoneyLogKey_SSTest extends ShopUserMoneyLogKey_SSTest_scaffolding {
// allCoveredLines:[5, 11, 15, 16, 19, 23, 24]

  @Test(timeout = 9000)
  public void test_getOrderId_0()  throws Throwable  {
      //caseID:8d1fa5ed7d4703501dda31faa4da8a80
      //CoveredLines: [5, 19]
      //Assert: assertNull(method_result);
      
      ShopUserMoneyLogKey shopUserMoneyLogKey0 = new ShopUserMoneyLogKey();
      
      //Call method: getOrderId
      Long long0 = shopUserMoneyLogKey0.getOrderId();
      
      //Test Result Assert
      assertNull(long0);
  }

  @Test(timeout = 9000)
  public void test_getUserId_1()  throws Throwable  {
      //caseID:3d7a562bab7b080e3a133c915df866e9
      //CoveredLines: [5, 11]
      //Assert: assertNull(method_result);
      
      ShopUserMoneyLogKey shopUserMoneyLogKey0 = new ShopUserMoneyLogKey();
      
      //Call method: getUserId
      Long long0 = shopUserMoneyLogKey0.getUserId();
      
      //Test Result Assert
      assertNull(long0);
  }

  @Test(timeout = 9000)
  public void test_setOrderId_2()  throws Throwable  {
      //caseID:21a60557f27daed71ab26d94dcd5d7fa
      //CoveredLines: [5, 23, 24]
      //Input_0_Long: 0L
      
      ShopUserMoneyLogKey shopUserMoneyLogKey0 = new ShopUserMoneyLogKey();
      Long long0 = new Long(0L);
      
      //Call method: setOrderId
      shopUserMoneyLogKey0.setOrderId(long0);
      
      //Test Result Assert
      assertNull(shopUserMoneyLogKey0.getUserId());
  }

  @Test(timeout = 9000)
  public void test_setUserId_3()  throws Throwable  {
      //caseID:ee64e137a611401856bd69fa0e859813
      //CoveredLines: [5, 15, 16]
      //Input_0_Long: 0L
      
      ShopUserMoneyLogKey shopUserMoneyLogKey0 = new ShopUserMoneyLogKey();
      Long long0 = new Long(0L);
      
      //Call method: setUserId
      shopUserMoneyLogKey0.setUserId(long0);
      
      //Test Result Assert
      assertNull(shopUserMoneyLogKey0.getOrderId());
  }
}
